/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.17 public/models/pickups/armor_small.glb 
*/

import React, { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'

export function ArmorSmallModel(props) {
  const modelRef = useRef()
  useFrame((state, delta, xrFrame) => 
  {
    modelRef.current.rotation.y += delta;
  })
  const { nodes, materials } = useGLTF('models/pickups/armor_small.glb')
  return (
    <group {...props} ref={modelRef} dispose={null}>
      <mesh geometry={nodes.armor_smoll.geometry} material={materials.armor} position={[0, 1.046, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.737 * props.scale, 1 * props.scale, 1 * props.scale]} />
    </group>
  )
}

useGLTF.preload('models/pickups/armor_small.glb')
