/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.17 public/models/pickups/health_big.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function HealthBigModel(props) {
  const { nodes, materials } = useGLTF('models/pickups/health_big.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 2.758, 0]} scale={[1.684 * props.scale, 2.601 * props.scale, 0.653 * props.scale]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials.plasmaammo} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.blue_glow} />
      </group>
    </group>
  )
}

useGLTF.preload('models/pickups/health_big.glb')
