/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.17 public/models/pickups/health_small.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function HealthSmallModel(props) {
  const { nodes, materials } = useGLTF('models/pickups/health_small.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.675 * props.scale}>
        <mesh geometry={nodes.Cube002.geometry} material={materials.white_transpar} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials.blue_glow} />
      </group>
    </group>
  )
}

useGLTF.preload('models/pickups/health_small.glb')
