/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/ammo/bullets.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bullets.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bullets.geometry} material={materials.bullets} />
    </group>
  )
}

useGLTF.preload('/bullets.glb')
