/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/weapons/har.glb 
*/

import { LoopOnce } from 'three'
import React, { useEffect, useRef, forwardRef, useImperativeHandle, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export const HARModel = forwardRef((props, ref) => {
  const modelRef = useRef()
  const { nodes, materials, animations } = useGLTF('/models/weapons/har.glb')
  const { actions } = useAnimations(animations, modelRef)
  const [ visibility, setVisibility ] = useState(false)

  useEffect(() => {
    for (const actionName in actions) {
      actions[actionName].setLoop(LoopOnce)
      actions[actionName].clampWhenFinished = 1
    }
    actions['har_idle'].reset().fadeIn(0).play()
  }, [])

  useImperativeHandle(ref, () => ({
    print_actions() { // for debugging purposes
      console.log(actions)
    }, 
    play_animation(name) {
      for (const key in actions) {
        if (key === name) {
          actions[key].reset().fadeIn(0).play();
        } else {
          actions[key].stop();
        }
      }
    },
    setVisibilityStatus(status) { // cursed
      setVisibility(status)
    }
  }))

  return (
    <group ref={modelRef} visible={visibility} {...props} dispose={null}>
      <group name="Scene">
        <group name="root_har" position={[0, 0, 0.889]} rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.Bone} />
          <skinnedMesh name="har" geometry={nodes.har.geometry} material={materials.har} skeleton={nodes.har.skeleton} />
        </group>
      </group>
    </group>
  )
})

useGLTF.preload('/har.glb')
