/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/weapons/plasma_gun.glb 
*/

import { LoopOnce } from 'three'
import React, { useEffect, useRef, forwardRef, useImperativeHandle, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export const PlasmaGunModel = forwardRef((props, ref) => {
  const modelRef = useRef()
  const { nodes, materials, animations } = useGLTF('/models/weapons/plasma_gun.glb')
  const { actions } = useAnimations(animations, modelRef)
  const [ visibility, setVisibility ] = useState(false)

  useEffect(() => {
    for (const actionName in actions) {
      actions[actionName].setLoop(LoopOnce)
      actions[actionName].clampWhenFinished = 1
    }
    actions['plasma_hold'].reset().fadeIn(0).play()
  }, [])
  
  useImperativeHandle(ref, () => ({
    print_actions() { // for debugging purposes
      console.log(actions)
    }, 
    play_animation(name) {
      for (const key in actions) {
        if (key === name) {
          actions[key].reset().fadeIn(0).play();
        } else {
          actions[key].stop();
        }
      }
    },
    setVisibilityStatus(status) { // cursed
      setVisibility(status)
    }
  }))
  return (
    <group ref={modelRef} {...props} visible={visibility} dispose={null}>
      <group name="Scene">
        <group name="root_plasma" scale={1.09}>
          <primitive object={nodes.plasma_root} />
          <group name="Cube">
            <skinnedMesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.002']} skeleton={nodes.Cube001.skeleton} />
            <skinnedMesh name="Cube001_1" geometry={nodes.Cube001_1.geometry} material={materials['Material.003']} skeleton={nodes.Cube001_1.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
})

useGLTF.preload('/plasma_gun.glb')
