/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/ammo/bullets.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function BulletsModel(props) {
  const modelRef = useRef()
  useFrame((state, delta, xrFrame) => 
  {
    modelRef.current.rotation.y += delta;
  })
  const { nodes, materials } = useGLTF('models/ammo/bullets.glb')
  return (
    <group {...props} ref={modelRef} dispose={null}>
      <mesh geometry={nodes.bullets.geometry} scale={props.scale} material={materials.bullets} />
    </group>
  )
}

useGLTF.preload('/bullets.glb')
