/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.17 public/models/ammo/cell.glb 
*/

import React, { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'

export function CellModel(props) {
  const modelRef = useRef()
  useFrame((state, delta, xrFrame) => 
  {
    modelRef.current.rotation.y += delta;
  })
  const { nodes, materials } = useGLTF('models/ammo/cell.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]} ref={modelRef} scale={[1.624 * props.scale, 1 * props.scale, 1.624 * props.scale]}>
        <mesh geometry={nodes.Cylinder003.geometry} material={materials.plasmaammo} />
        <mesh geometry={nodes.Cylinder003_1.geometry} material={materials.purple_glow} />
      </group>
    </group>
  )
}

useGLTF.preload('/cell.glb')
