/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/ammo/rocket.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function RocketModel(props) {
  const { nodes, materials } = useGLTF('models/ammo/rocket.glb')
  const modelRef = useRef()
  useFrame((state, delta, xrFrame) => 
  {
    modelRef.current.rotation.y += delta;
  })
  return (
    <group {...props} ref={modelRef} dispose={null}>
      <mesh geometry={nodes.rocket.geometry} material={materials['Material.001']} position={[0, 0, 0]} 
      scale={[0.4 * props.scale, 1 * props.scale, 0.4 * props.scale]} />
    </group>
  )
}

useGLTF.preload('/rocket.glb')
