/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.17 public/models/ammo/shells.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function ShellsModel (props) {
  const modelRef = useRef()
  useFrame((state, delta, xrFrame) => 
  {
    modelRef.current.rotation.y += delta;
  })
  const { nodes, materials } = useGLTF('models/ammo/shells.glb')
  return (
    <group {...props} ref={modelRef} dispose={null}>
      <mesh geometry={nodes.shells.geometry} material={materials.shells_material} 
      position={[0, 0, 0]} scale={[1 * props.scale, 0.157 * props.scale, 1.902 * props.scale]} />
    </group>
  )
}

useGLTF.preload('/shells.glb')
